base_model: "Qwen/Qwen2.5-1.5B"
run_name: "Original_BASE_0.5B_512_N8_D8"
datasets: 
  - "amc23"
  - "gsm8k"
  - "math500"
max_seq_length: 1024
temperature: 0.9
max_tokens: 512
batch_size: 512
sample_cnt: 5
repeat_cnt: 5

hydra:
  run:
    dir: outputs
  output_subdir: null
  job:
    chdir: false
