base_model: "Qwen/Qwen2.5-Math-1.5B-Instruct"
run_name: "math_instruct_math_64"
datasets: 
  # - "amc23"
  # - "gsm8k"
  - "math500"
max_seq_length: 1024
temperature: 0.9
max_tokens: 1024
batch_size: 512
sample_cnt: 5
repeat_cnt: 5